export default function Privacy() {
  return (
    <div className="max-w-3xl mx-auto px-4 sm:px-6 py-10">
      <h1 className="font-display text-3xl sm:text-4xl font-bold text-gray-900 mb-2">Privacy Policy</h1>
      <p className="text-sm text-gray-500 mb-10">Last updated: 6 May 2026</p>

      <div className="prose prose-sm max-w-none text-gray-700 space-y-6 leading-relaxed">

        <section>
          <h2 className="font-display text-xl font-semibold text-gray-900 mt-2 mb-3">1. Who we are</h2>
          <p>
            <strong>Parent2Parent (Pty) Ltd</strong> (registration number 2026/208826/07) is the
            responsible party (data controller) for the personal information collected and
            processed through parent2parent.co.za (the "Platform").
          </p>
          <p>
            This Privacy Policy explains what personal information we collect, why we collect it,
            how we use and protect it, and your rights under the Protection of Personal
            Information Act 4 of 2013 ("POPIA").
          </p>
          <p>
            <strong>Information Officer:</strong> Dean Cohen<br />
            <strong>Contact:</strong>{' '}
            <a href="mailto:support@parent2parent.co.za" className="text-primary hover:underline">support@parent2parent.co.za</a><br />
            <strong>Address:</strong> 18 Southfield Road, Plumstead, Cape Town, Western Cape, 7801
          </p>
        </section>

        <section>
          <h2 className="font-display text-xl font-semibold text-gray-900 mt-6 mb-3">2. The information we collect</h2>
          <p>We collect personal information you provide directly and information generated by your use of the Platform.</p>

          <h3 className="font-semibold text-gray-800 mt-4 mb-2">2.1 Information you provide</h3>
          <ul className="list-disc pl-6 space-y-1.5">
            <li><strong>Account information:</strong> name, email address, password (hashed), province, mobile number.</li>
            <li><strong>Seller profile information:</strong> physical street address, city, postal code, profile photo, bio.</li>
            <li><strong>Listing content:</strong> photographs, descriptions, prices and condition information you upload.</li>
            <li><strong>Order information:</strong> delivery address, delivery instructions, the items you buy or sell.</li>
            <li><strong>Payment information:</strong> processed by our payment provider Yoco. We do not store your card details on our servers — Yoco is PCI-DSS compliant and handles cardholder data directly.</li>
            <li><strong>Dispute information:</strong> reasons, descriptions and evidence photos you submit when raising a return.</li>
            <li><strong>Support and communication records:</strong> messages you send to us by email or through the Platform.</li>
          </ul>

          <h3 className="font-semibold text-gray-800 mt-4 mb-2">2.2 Information we generate or collect automatically</h3>
          <ul className="list-disc pl-6 space-y-1.5">
            <li><strong>Technical information:</strong> IP address, browser type, device type, operating system, language preference.</li>
            <li><strong>Usage information:</strong> pages visited, listings viewed, search queries, listings saved.</li>
            <li><strong>Authentication cookies:</strong> session tokens used to keep you logged in.</li>
          </ul>
          <p className="mt-2">
            We do not currently use third-party analytics, advertising trackers or marketing
            cookies. If we add any in future, we will update this Policy and provide an
            appropriate cookie notice.
          </p>
        </section>

        <section>
          <h2 className="font-display text-xl font-semibold text-gray-900 mt-6 mb-3">3. How we use your information</h2>
          <p>We process personal information for the following purposes:</p>
          <ul className="list-disc pl-6 space-y-1.5">
            <li><strong>Provide the Platform:</strong> create and manage your account, display your listings, process orders, hold escrow, arrange courier collection and delivery.</li>
            <li><strong>Communicate with you:</strong> send order confirmations, dispute updates, courier tracking and other transactional emails.</li>
            <li><strong>Resolve disputes:</strong> review evidence, communicate with both parties, and process refunds where applicable.</li>
            <li><strong>Operate Buyer Protection:</strong> hold and release escrow funds, issue refunds, and manage payouts to Sellers.</li>
            <li><strong>Improve the Platform:</strong> analyse usage patterns, fix bugs, and develop new features.</li>
            <li><strong>Prevent fraud and abuse:</strong> detect and prevent fraudulent transactions, account takeovers, and breaches of our Terms.</li>
            <li><strong>Comply with legal obligations:</strong> respond to lawful requests from regulators or law enforcement, and meet our tax and accounting obligations.</li>
            <li><strong>Marketing:</strong> we may send marketing emails about new features, tips and offers if you opt in. You can opt out at any time via the unsubscribe link in any marketing email or by emailing us.</li>
          </ul>
        </section>

        <section>
          <h2 className="font-display text-xl font-semibold text-gray-900 mt-6 mb-3">4. Lawful basis for processing</h2>
          <p>Under POPIA we rely on the following grounds:</p>
          <ul className="list-disc pl-6 space-y-1.5">
            <li><strong>Performance of a contract:</strong> processing necessary to operate your account, fulfil orders and resolve disputes.</li>
            <li><strong>Consent:</strong> for marketing communications and any future analytics or marketing cookies.</li>
            <li><strong>Legitimate interests:</strong> fraud prevention, platform security, and improving our services.</li>
            <li><strong>Legal obligation:</strong> tax records, regulatory compliance and lawful requests.</li>
          </ul>
        </section>

        <section>
          <h2 className="font-display text-xl font-semibold text-gray-900 mt-6 mb-3">5. Sharing your information</h2>
          <p>We share personal information only as needed to provide the Platform, and only with the following categories of recipients:</p>

          <h3 className="font-semibold text-gray-800 mt-4 mb-2">Other Users</h3>
          <ul className="list-disc pl-6 space-y-1.5">
            <li>Buyers see the Seller's first name, profile photo, and the Seller's province and city.</li>
            <li>Sellers see the Buyer's first name and the delivery city. Full delivery address is shared only with the courier driver, not the Seller.</li>
            <li>If a return is raised, the Seller's return address is shared with the Buyer so the item can be returned. The Buyer's tracking number is shared with the Seller.</li>
          </ul>

          <h3 className="font-semibold text-gray-800 mt-4 mb-2">Service providers (operators under POPIA)</h3>
          <p>The following providers process personal information on our behalf, under written agreements that comply with POPIA:</p>
          <ul className="list-disc pl-6 space-y-1.5">
            <li><strong>Yoco (Yoco Technologies (Pty) Ltd):</strong> payment processing and refunds.</li>
            <li><strong>The Courier Guy (TCG Couriers (Pty) Ltd):</strong> collection and delivery of parcels — receives the Buyer's delivery address, the Seller's collection address, and both parties' contact numbers for delivery purposes.</li>
            <li><strong>Brevo (Sendinblue SAS):</strong> transactional and marketing email delivery.</li>
            <li><strong>Cloudinary:</strong> hosting of listing and dispute evidence photos.</li>
            <li><strong>Google Maps API:</strong> address validation and delivery routing.</li>
          </ul>

          <h3 className="font-semibold text-gray-800 mt-4 mb-2">Legal and regulatory</h3>
          <p>
            We may disclose personal information if required by law, court order, or lawful
            request from a regulator or law enforcement agency, and where necessary to protect
            our rights, property or safety, or those of our Users.
          </p>

          <p className="mt-3">We do not sell or rent your personal information to third parties.</p>
        </section>

        <section>
          <h2 className="font-display text-xl font-semibold text-gray-900 mt-6 mb-3">6. Cross-border transfers</h2>
          <p>
            We aim to host personal information on infrastructure located in South Africa where
            possible. Some of our service providers (notably Cloudinary, Brevo and Google Maps)
            may process information outside South Africa. Where information is transferred
            internationally, we rely on contractual safeguards and the operators' POPIA-equivalent
            data-protection commitments to ensure your information remains protected to a
            standard substantially similar to POPIA.
          </p>
        </section>

        <section>
          <h2 className="font-display text-xl font-semibold text-gray-900 mt-6 mb-3">7. How long we keep your information</h2>
          <p>We retain personal information for as long as needed for the purposes set out in this Policy and to comply with our legal obligations:</p>
          <ul className="list-disc pl-6 space-y-1.5">
            <li><strong>Account information:</strong> for as long as your account is active, plus a reasonable period after closure to handle disputes, refunds and chargebacks.</li>
            <li><strong>Order, payment and tax records:</strong> at least five years from the end of the financial year in which the transaction occurred (as required by South African tax law).</li>
            <li><strong>Dispute records and evidence photos:</strong> at least three years after the dispute is resolved.</li>
            <li><strong>Marketing preferences:</strong> until you withdraw consent, plus a record of the withdrawal itself.</li>
          </ul>
          <p>When information is no longer needed we securely delete or anonymise it.</p>
        </section>

        <section>
          <h2 className="font-display text-xl font-semibold text-gray-900 mt-6 mb-3">8. Security</h2>
          <p>
            We take appropriate, reasonable technical and organisational measures to protect
            personal information from loss, damage, unauthorised access, alteration or
            disclosure. These include encrypted connections (HTTPS), hashed passwords,
            access controls, and reputable third-party providers for payments and storage.
          </p>
          <p>
            No system is perfectly secure. If a security compromise occurs that is reasonably
            likely to result in real risk of harm, we will notify the affected Users and the
            Information Regulator as required by POPIA.
          </p>
        </section>

        <section>
          <h2 className="font-display text-xl font-semibold text-gray-900 mt-6 mb-3">9. Your rights under POPIA</h2>
          <p>You have the following rights in respect of your personal information:</p>
          <ul className="list-disc pl-6 space-y-1.5">
            <li><strong>Access:</strong> request a copy of the personal information we hold about you.</li>
            <li><strong>Correction:</strong> ask us to correct information that is inaccurate or out of date.</li>
            <li><strong>Deletion:</strong> ask us to delete information we no longer need (subject to legal retention obligations).</li>
            <li><strong>Object:</strong> object to processing on grounds of legitimate interest, or to direct marketing.</li>
            <li><strong>Withdraw consent:</strong> withdraw consent at any time where we rely on consent to process your information.</li>
            <li><strong>Lodge a complaint:</strong> with the Information Regulator if you believe we have not handled your information in accordance with POPIA.</li>
          </ul>
          <p>
            To exercise any of these rights, contact us at{' '}
            <a href="mailto:support@parent2parent.co.za" className="text-primary hover:underline">support@parent2parent.co.za</a>.
            We will respond within a reasonable period, typically within 30 days.
          </p>
          <p className="mt-3">
            <strong>Information Regulator (South Africa):</strong><br />
            JD House, 27 Stiemens Street, Braamfontein, Johannesburg, 2001<br />
            Email: <a href="mailto:complaints.IR@justice.gov.za" className="text-primary hover:underline">complaints.IR@justice.gov.za</a><br />
            Web: <a href="https://inforegulator.org.za" target="_blank" rel="noopener noreferrer" className="text-primary hover:underline">inforegulator.org.za</a>
          </p>
        </section>

        <section>
          <h2 className="font-display text-xl font-semibold text-gray-900 mt-6 mb-3">10. Children</h2>
          <p>
            The Platform is intended for adults aged 18 and older. We do not knowingly collect
            personal information from children. If you believe a child has provided us with
            personal information, please contact us and we will delete it.
          </p>
        </section>

        <section>
          <h2 className="font-display text-xl font-semibold text-gray-900 mt-6 mb-3">11. Cookies and similar technologies</h2>
          <p>
            We use only the cookies necessary to keep you logged in and to operate core Platform
            features. We do not currently use third-party analytics cookies, advertising cookies
            or marketing pixels. If we introduce non-essential cookies in future, we will update
            this Policy and ask for your consent before they are set.
          </p>
        </section>

        <section>
          <h2 className="font-display text-xl font-semibold text-gray-900 mt-6 mb-3">12. Changes to this Policy</h2>
          <p>
            We may update this Privacy Policy from time to time. The current version will always
            be available at parent2parent.co.za/privacy with a "Last updated" date. Material
            changes will be communicated by email or in-app notice.
          </p>
        </section>

        <section>
          <h2 className="font-display text-xl font-semibold text-gray-900 mt-6 mb-3">13. Contact us</h2>
          <p>
            For any privacy questions, requests or complaints, contact our Information Officer:
          </p>
          <p>
            <strong>Dean Cohen — Information Officer</strong><br />
            Parent2Parent (Pty) Ltd<br />
            18 Southfield Road, Plumstead, Cape Town, Western Cape, 7801<br />
            <a href="mailto:support@parent2parent.co.za" className="text-primary hover:underline">support@parent2parent.co.za</a>
          </p>
        </section>

      </div>
    </div>
  );
}
